volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: liectaski/kittygram_backend:latest
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    image: liectaski/kittygram_frontend:latest
    container_name: frontend
    restart: always
    volumes:
      - static:/app/static/

  gateway:
    image: liectaski/kittygram_gateway:latest
    container_name: gateway
    restart: always
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/app/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
